apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
      initContainers:
      - name: mongo-init
        image: mongo:latest
        command:
          - /bin/sh
          - "-c"
          - |
            mongo <<EOF
            use $INIT_DB;
            db.createUser({
                user: "$MONGO_DB_USERNAME",
                pwd: "$MONGO_DB_PASSWORD",
                roles: [{ role: "readWrite", db: "$INIT_DB" }]
            });
            EOF
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: INIT_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: init-db
        - name: MONGO_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-username
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017

---

# mongo-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi   # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce   # The volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain   # Or 'Recycle'/'Delete', depending on your use case
  storageClassName: csi-disk
  hostPath:             # Using hostPath for local storage; use another provisioner for cloud
    path: "/data/mongo"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-disk


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  init-db: "bookstore"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-username: cmFsZg==
  mongo-password: UXdlcnR5MTIz


