apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cmFsZg==        # base64 encoded "ralf"
  POSTGRES_PASSWORD: UXdlcnR5MTIzNA== # base64 encoded "Qwerty123"
  POSTGRES_DB: Ym9va3N0b3JlX2F1dGg=   # base64 encoded "bookstore_auth"