apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      imagePullSecrets:
        - name: default-secret    
      containers:
      - name: inventory-service
        image: swr.af-south-1.myhuaweicloud.com/ralf/inventory-api:efd2af4df959640451a8c4c47430a8ee9211dc3e
        ports:
        - containerPort: 3001
        # envFrom:
        # - configMapRef:
        #     name: inventory-configs
        env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: MONGO_HOST
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: MONGO_DB
            - name: TOKEN_VERIFICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: TOKEN_VERIFICATION_URL
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: REDIS_URI
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookms-secret
                  key: MONGO_PASSWORD      
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: bookms-secret
                  key: MONGO_USER                    
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
