apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      imagePullSecrets:
        - name: default-secret    
      containers:
      - name: inventory-service
        image: swr.af-south-1.myhuaweicloud.com/ralf/inventory-api:efd2af4df959640451a8c4c47430a8ee9211dc3e
        ports:
        - containerPort: 5000
        # envFrom:
        # - configMapRef:
        #     name: inventory-config
        env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: MONGO_URI
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: REDIS_URI
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
