# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookms-config
  namespace: default
data:
  MONGODB_URI: "mongodb://mongo:27017/auth-service"
  POSTGRES_USER: "ralf"
  POSTGRES_PASSWORD: "Qwerty_123"
  POSTGRES_DB: "bookstore_auth"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  RABBITMQ_URL: "amqp://rabbitmq"
  JWT_SECRET: "ralf"

