name: CI/CD for book microservice
on:
  push:
    branches:
      - main  # Trigger CI/CD when code is pushed to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1

      - name: Build and push auth service
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/auth-api:${{ github.sha }} auth-service/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/auth-api:${{ github.sha }}

      - name: Build and push inventory service
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/inventory-api:${{ github.sha }} inventory-service/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/inventory-api:${{ github.sha }}          

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure kubectl for Huawei Cloud CCE
        run: |
          sudo mkdir -p $HOME/.kube
          sudo chown -R runner:runner $HOME/.kube
          export KUBECONFIG=$HOME/.kube/config
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $KUBECONFIG

      - name: Update deployment
        run: |
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    

      - name: Debugging CCE access
        run: |
          kubectl version
          kubectl cluster-info

      - name: Deploy manifest
        run: |
          kubectl apply -f manifest/
