name: Build to Harbor
on:
  push:
    branches:
      - main  # Trigger CI/CD when code is pushed to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Harbor Container Registry
        uses: docker/login-action@v3
        with:
          registry: demo.goharbor.io
          username: rafel0
          password: ${{ secrets.HARBOR_PASS }}

      - name: Build and push auth service
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/auth-api:${{ github.sha }} 
          docker push swr.af-south-1.myhuaweicloud.com/ralf/auth-api:${{ github.sha }}

          docker build -t demo.goharbor.io/hades/auth-service auth-service/
          docker push demo.goharbor.io/hades/auth-service
